import type { ChapterCatalog, DraftSpec } from './phase1-types.ts';
import { choose, wrong } from './phase1-types.ts';

const catalog:Record<string,DraftSpec[]>={
  '2.1|concept':[
    {blueprint_section:'2.1',subtype:'concept',stem:'两个有限长序列分别在 \\(0\\le n\\le L_x-1\\) 与 \\(0\\le n\\le L_h-1\\) 非零，其卷积长度通常是多少？',correct:'\\(L_x+L_h-1\\)',wrong:[wrong('\\(L_x+L_h\\)','WRONG_SUPPORT_INTERVAL'),wrong('\\(\\max(L_x,L_h)\\)','WRONG_SUPPORT_INTERVAL'),wrong('\\(L_xL_h\\)','WRONG_SUPPORT_INTERVAL')],explanation:'正确：支撑端点相加，非零索引从0到 \\(L_x+L_h-2\\)，共 \\(L_x+L_h-1\\) 点。错项混淆端点与点数。易错点：长度要在最大索引基础上再加1。'},
    {blueprint_section:'2.1',subtype:'concept',stem:'离散卷积的交换性表示为哪一项？',correct:'\\(x[n]*h[n]=h[n]*x[n]\\)',wrong:[wrong('\\(x[n]*h[n]=x[n]h[n]\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(x[n]*h[n]=h[-n]*x[n]\\)','MISSING_TIME_REVERSAL'),wrong('\\(x[n]*h[n]=x[-n]*h[-n]\\)','WRONG_CONVOLUTION_INDEX')],explanation:'正确：交换两个序列不改变卷积和。错项把卷积写成乘积或引入额外反转。易错点：定义式中可以换元证明交换性。'}
  ],
  '2.1|formula':[
    {blueprint_section:'2.1',subtype:'formula',stem:'序列与移位冲激卷积：\\(x[n]*\\delta[n-n_0]\\) 等于什么？',correct:'\\(x[n-n_0]\\)',wrong:[wrong('\\(x[n+n_0]\\)','WRONG_SHIFT_DIRECTION'),wrong('\\(x[n]\\delta[n-n_0]\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(x[n_0]\\)','WRONG_CONVOLUTION_INDEX')],explanation:'正确：移位冲激在卷积中把序列整体延迟 \\(n_0\\)。错项写反平移、混淆相乘或只做取样。易错点：与冲激相乘是取样，与冲激卷积是移位。'}
  ],
  '2.1|error_discrimination':[
    {blueprint_section:'2.1',subtype:'error_discrimination',stem:'卷积和 \\(\\sum_k x[k]h[n-k]\\) 中，学生把 \\(h[n-k]\\) 改成 \\(h[k-n]\\)。核心错误是什么？',correct:'翻转方向改变，所得一般不是原卷积',wrong:[wrong('只是更换求和变量，结果总相同','WRONG_CONVOLUTION_INDEX'),wrong('仅少了一个尺度因子','MISS_SCALE_FACTOR'),wrong('连续时间才需要翻转，离散时间不需要','CONFUSE_CT_DT')],explanation:'正确：\\(h[n-k]\\) 与 \\(h[k-n]\\) 的反转和平移方向不同，不能直接互换。错项把结构变化当作哑变量替换。易错点：换元时必须同时改变整个被积式和范围。'},
    {blueprint_section:'2.1',subtype:'error_discrimination',stem:'学生写 \\(y[n]=\\sum_k x[n-k]h[n-k]\\) 作为卷积。主要问题是什么？',correct:'两个信号都被同样移位，缺少固定的 \\(x[k]\\) 或 \\(h[k]\\)',wrong:[wrong('只需把求和改成积分','CONFUSE_CT_DT'),wrong('应该再乘 \\(2\\pi\\)','MISSING_2PI'),wrong('卷积不能使用变量 \\(k\\)','WRONG_CONVOLUTION_INDEX')],explanation:'正确：标准卷积中一个序列以 \\(k\\) 取样，另一个翻转平移。错项没有修复两个因子同时随 \\(n-k\\) 变化。易错点：不要让两个因子都承担同一个滑动。'},
    {blueprint_section:'2.1',subtype:'error_discrimination',stem:'若 \\(x[n]\\) 仅在 \\(1\\le n\\le3\\) 非零，\\(h[n]\\) 仅在 \\(-2\\le n\\le0\\) 非零，则卷积可能非零的区间是什么？',correct:'\\(-1\\le n\\le3\\)',wrong:[wrong('\\(1\\le n\\le3\\)','WRONG_SUPPORT_INTERVAL'),wrong('\\(-2\\le n\\le0\\)','WRONG_SUPPORT_INTERVAL'),wrong('\\(-3\\le n\\le3\\)','WRONG_SUPPORT_INTERVAL')],explanation:'正确：卷积支撑端点分别相加，起点 \\(1+(-2)=-1\\)，终点 \\(3+0=3\\)。错项只保留某一支撑或错误扩展。易错点：支撑区间做Minkowski和。'},
    {blueprint_section:'2.1',subtype:'error_discrimination',stem:'对 \\(x[n]=u[n]\\)、\\(h[n]=u[n]\\)，卷积 \\(y[n]\\) 是哪一个？',correct:'\\((n+1)u[n]\\)',wrong:[wrong('\\(u[n]\\)','FORGOT_INTEGRATION'),wrong('\\(nu[n]\\)','WRONG_CONVOLUTION_INDEX'),wrong('\\(u[-n]\\)','WRONG_SHIFT_DIRECTION')],explanation:'正确：当 \\(n\\ge0\\) 时可相加的整数索引有 \\(n+1\\) 个。错项忘记累加点数、少算端点或反转支撑。易错点：离散求和包含两个端点。'}
  ],
  '2.2|concept':[
    {blueprint_section:'2.2',subtype:'concept',stem:'若两个连续信号的非零支撑分别为 \\([a,b]\\) 与 \\([c,d]\\)，其卷积支撑至多位于哪里？',correct:'\\([a+c,b+d]\\)',wrong:[wrong('\\([a-c,b-d]\\)','WRONG_SUPPORT_INTERVAL'),wrong('\\([\\min(a,c),\\max(b,d)]\\)','WRONG_SUPPORT_INTERVAL'),wrong('\\([ac,bd]\\)','WRONG_SUPPORT_INTERVAL')],explanation:'正确：卷积中可重叠位置由两支撑端点相加决定。错项使用相减、并集或乘积。易错点：先用支撑和可快速排除大量答案。'},
    {blueprint_section:'2.2',subtype:'concept',stem:'若 \\(y(t)=x(t)*h(t)\\)，且相关积分存在，则 \\(y(t)\\) 的总面积满足什么关系？',correct:'\\(\\int y(t)dt=(\\int x(t)dt)(\\int h(t)dt)\\)',wrong:[wrong('\\(\\int y(t)dt=\\int x(t)dt+\\int h(t)dt\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(\\int y(t)dt=\\int x(t)h(t)dt\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(\\int y(t)dt=0\\)','FORGOT_INTEGRATION')],explanation:'正确：交换积分次序后，卷积的总面积等于两信号总面积之积。错项把卷积当加法、内积或无条件判零。易错点：这是用面积快速验算卷积结果的方法。'}
  ],
  '2.2|formula':[
    {blueprint_section:'2.2',subtype:'formula',stem:'连续时间卷积积分的标准形式是哪一个？',correct:'\\(y(t)=\\int_{-\\infty}^{\\infty}x(\\tau)h(t-\\tau)d\\tau\\)',wrong:[wrong('\\(y(t)=\\int x(t)h(t)dt\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(y(t)=\\int x(t-\\tau)h(t-\\tau)d\\tau\\)','BOTH_SIGNALS_SHIFTED'),wrong('\\(y(t)=\\sum_kx[k]h[n-k]\\)','CONFUSE_CT_DT')],explanation:'正确：积分变量为 \\(\\tau\\)，一个信号固定为 \\(x(\\tau)\\)，另一个写成 \\(h(t-\\tau)\\)。错项混淆乘积、同时移位或离散卷积。易错点：积分结果只保留变量 \\(t\\)。'},
    {blueprint_section:'2.2',subtype:'formula',stem:'矩形脉冲 \\(x(t)=u(t)-u(t-1)\\) 与自身卷积在 \\(0\\le t\\le1\\) 时等于什么？',correct:'\\(y(t)=t\\)',wrong:[wrong('\\(y(t)=1-t\\)','WRONG_SHIFT_DIRECTION'),wrong('\\(y(t)=1\\)','FORGOT_INTEGRATION'),wrong('\\(y(t)=t^2\\)','CONFUSE_CONVOLUTION_MULTIPLICATION')],explanation:'正确：在 \\(0\\le t\\le1\\) 时两单位宽矩形的重叠长度为 \\(t\\)。错项使用下降段、忽略重叠长度或错误相乘。易错点：卷积值等于“重叠面积”，分段点由支撑端点决定。'}
  ],
  '2.2|error_discrimination':[
    {blueprint_section:'2.2',subtype:'error_discrimination',stem:'把 \\(h(t-\\tau)\\) 画成 \\(\\tau\\) 的函数时，哪一步不可省略？',correct:'先把 \\(h(\\tau)\\) 关于原点翻转',wrong:[wrong('先对幅度取平方','FORGOT_MAGNITUDE_SQUARED'),wrong('把两个信号都向右移 \\(t\\)','BOTH_SIGNALS_SHIFTED'),wrong('把积分改为求和','CONFUSE_CT_DT')],explanation:'正确：\\(h(t-\\tau)=h[-(\\tau-t)]\\)，必须包含时间反转。错项引入无关平方、双重移位或离散化。易错点：翻转相对于积分变量 \\(\\tau\\) 进行。'},
    {blueprint_section:'2.2',subtype:'error_discrimination',stem:'在 \\(y(t)=\\int x(\\tau)h(t-\\tau)d\\tau\\) 中，作图滑动的参数是哪一个？',correct:'\\(t\\)',wrong:[wrong('\\(\\tau\\)','WRONG_CONVOLUTION_INDEX'),wrong('\\(t-\\tau\\)','WRONG_CONVOLUTION_INDEX'),wrong('积分结果没有自变量','CONFUSE_CT_DT')],explanation:'正确：\\(\\tau\\) 是积分变量，\\(t\\) 决定翻转信号的滑动位置。错项混淆了哑变量与输出变量。易错点：积分结束后 \\(\\tau\\) 必须消失。'},
    {blueprint_section:'2.2',subtype:'error_discrimination',stem:'若 \\(x(t)\\) 支撑在 \\([0,2]\\)，\\(h(t)\\) 支撑在 \\([1,4]\\)，学生称卷积从 \\(t=1\\) 到 \\(t=4\\) 非零。错误是什么？',correct:'终点应为 \\(2+4=6\\)，支撑为 \\([1,6]\\)',wrong:[wrong('起点应为-1，终点应为2','WRONG_SUPPORT_INTERVAL'),wrong('支撑应取两区间交集 \\([1,2]\\)','WRONG_SUPPORT_INTERVAL'),wrong('卷积没有有限支撑','WRONG_SUPPORT_INTERVAL')],explanation:'正确：卷积支撑端点相加，起点0+1，终点2+4。错项只沿用某一输入支撑或取交集。易错点：卷积支撑不是普通区间交集。'},
    {blueprint_section:'2.2',subtype:'error_discrimination',stem:'对任意信号 \\(x(t)\\)，\\(x(t)*\\delta(t+2)\\) 等于什么？',correct:'\\(x(t+2)\\)',wrong:[wrong('\\(x(t-2)\\)','WRONG_SHIFT_DIRECTION'),wrong('\\(x(-t+2)\\)','MISSING_TIME_REVERSAL'),wrong('\\(x(-2)\\delta(t+2)\\)','CONFUSE_CONVOLUTION_MULTIPLICATION')],explanation:'正确：与位于 \\(-2\\) 的冲激卷积使信号提前2。错项写反平移、额外反转或混淆冲激相乘。易错点：\\(\\delta(t-t_0)\\) 卷积得到 \\(x(t-t_0)\\)。'},
    {blueprint_section:'2.2',subtype:'error_discrimination',stem:'学生将 \\(\\frac{d}{dt}[x(t)*h(t)]\\) 写成 \\(x(t)h(t)\\)。正确关系是什么？',correct:'可写成 \\(x^{\\prime}(t)*h(t)\\) 或 \\(x(t)*h^{\\prime}(t)\\)',wrong:[wrong('等于 \\(x^{\\prime}(t)h^{\\prime}(t)\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('等于 \\(x(t)*h(t)\\)，微分无影响','OUTPUT_NOT_DIFFERENTIATED'),wrong('只能写成 \\(x^{\\prime}(t)*h^{\\prime}(t)\\)','WRONG_DIFFERENTIATION_FACTOR')],explanation:'正确：卷积微分可把一次微分作用到任一因子。错项把卷积改成乘积、漏微分或让两边同时微分。易错点：总共只增加一次微分。'},
    {blueprint_section:'2.2',subtype:'error_discrimination',stem:'两单位面积矩形脉冲卷积后，输出总面积应是多少？',correct:'\\(1\\)',wrong:[wrong('\\(2\\)','MISS_FACTOR_2'),wrong('\\(1/2\\)','MISS_SCALE_FACTOR'),wrong('必须为0','FORGOT_INTEGRATION')],explanation:'正确：卷积总面积等于两个输入面积之积，即1。错项把面积相加、平均或误判抵消。易错点：峰值可能改变，但总面积仍由面积乘积决定。'},
    {blueprint_section:'2.2',subtype:'error_discrimination',stem:'若 \\(x(t)\\) 与 \\(h(t)\\) 都是实偶信号，则它们的卷积具有什么对称性？',correct:'仍为实偶信号',wrong:[wrong('必为实奇信号','SIGN_ERROR'),wrong('一般为复信号','IGNORED_CONJUGATE_SYMMETRY'),wrong('必为因果信号','CAUSALITY_ERROR')],explanation:'正确：偶函数卷积保持偶性，实信号卷积仍实。错项混淆奇偶、实复与因果性。易错点：偶信号若非零通常不因果。'}
  ],
  '2.3|concept':[
    {blueprint_section:'2.3',subtype:'concept',stem:'两个LTI系统串联时，总冲激响应是什么？',correct:'\\(h(t)=h_1(t)*h_2(t)\\)',wrong:[wrong('\\(h(t)=h_1(t)h_2(t)\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(h(t)=h_1(t)+h_2(t)\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(h(t)=h_1(t)-h_2(t)\\)','SIGN_ERROR')],explanation:'正确：第一级输出再与第二级冲激响应卷积，合成为两冲激响应的卷积。错项把串联误作乘积或加减。易错点：频域串联才是频率响应相乘。'},
    {blueprint_section:'2.3',subtype:'concept',stem:'离散时间LTI系统因果的充要条件是什么？',correct:'\\(h[n]=0\\)，对所有 \\(n<0\\)',wrong:[wrong('\\(h[n]=0\\)，对所有 \\(n>0\\)','CAUSALITY_ERROR'),wrong('\\(h[0]=0\\)','CAUSALITY_ERROR'),wrong('\\(\\sum_n|h[n]|<\\infty\\)','CAUSALITY_ERROR')],explanation:'正确：因果输出只能使用当前和过去输入，因此冲激响应负时间部分必须为0。错项写反支撑或混入稳定条件。易错点：绝对可和对应BIBO稳定，不是因果。'},
    {blueprint_section:'2.3',subtype:'concept',stem:'连续时间LTI系统BIBO稳定的充要条件是什么？',correct:'\\(\\int_{-\\infty}^{\\infty}|h(t)|dt<\\infty\\)',wrong:[wrong('\\(\\int h(t)dt=0\\)','CONFUSE_ENERGY_POWER'),wrong('\\(h(t)=0\\) 对 \\(t<0\\)','CAUSALITY_ERROR'),wrong('\\(\\int |h(t)|^2dt<\\infty\\)','FORGOT_MAGNITUDE_SQUARED')],explanation:'正确：冲激响应绝对可积保证任意有界输入产生有界输出。错项混入零面积、因果或能量条件。易错点：稳定性需要绝对值的一次积分。'},
    {blueprint_section:'2.3',subtype:'concept',stem:'LTI系统对复指数输入 \\(e^{st}\\) 的零状态响应具有什么形式？',correct:'\\(H(s)e^{st}\\)，若相应积分收敛',wrong:[wrong('\\(H(t)e^{st}\\)','INVALID_TIME_SCALING_FOR_LTI'),wrong('\\(e^{H(s)t}\\)','LINEARITY_ERROR'),wrong('\\(H(s+t)\\)','TIME_INVARIANCE_ERROR')],explanation:'正确：复指数是LTI系统的特征函数，系统只改变复幅度。错项混淆频率响应、自变量和指数结构。易错点：必须同时注意收敛条件。'}
  ],
  '2.3|formula':[
    {blueprint_section:'2.3',subtype:'formula',stem:'两个LTI系统并联后输出相加，总冲激响应是多少？',correct:'\\(h(t)=h_1(t)+h_2(t)\\)',wrong:[wrong('\\(h_1(t)*h_2(t)\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(h_1(t)h_2(t)\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('\\(h_1(t)-h_2(t)\\)','SIGN_ERROR')],explanation:'正确：并联支路对同一输入分别响应，输出相加，对应冲激响应相加。错项把并联与串联或频域乘法混淆。易错点：串联卷积，并联相加。'},
    {blueprint_section:'2.3',subtype:'formula',stem:'若LTI系统阶跃响应为 \\(s(t)=(1-e^{-2t})u(t)\\)，其冲激响应为哪一个？',correct:'\\(h(t)=2e^{-2t}u(t)\\)',wrong:[wrong('\\(h(t)=(1-e^{-2t})u(t)\\)','OUTPUT_NOT_DIFFERENTIATED'),wrong('\\(h(t)=-2e^{-2t}u(t)\\)','SIGN_ERROR'),wrong('\\(h(t)=\\frac12e^{-2t}u(t)\\)','MISS_SCALE_FACTOR')],explanation:'正确：\\(h=ds/dt\\)；该阶跃响应在原点连续且 \\(s(0)=0\\)，没有附加冲激项。错项漏微分、符号错或系数倒置。易错点：若阶跃响应在原点有跳变，微分还会产生冲激。'}
  ],
  '2.3|error_discrimination':[
    {blueprint_section:'2.3',subtype:'error_discrimination',stem:'学生认为“任意LTI系统都可把 \\(x(at)\\) 的输出写成 \\(y(at)/|a|\\)”。问题在哪里？',correct:'LTI只保证时移与线性，通常不保证时间尺度变换可交换',wrong:[wrong('只需去掉 \\(|a|\\)，写成 \\(y(at)\\)','INVALID_TIME_SCALING_FOR_LTI'),wrong('该结论只对离散时间成立','CONFUSE_CT_DT'),wrong('LTI系统不能处理缩放后的输入','INVALID_TIME_SCALING_FOR_LTI')],explanation:'正确：时间尺度性质属于傅里叶变换，不是一般LTI映射性质。错项只是修改系数或换时间类型。易错点：不要把变换性质直接当系统性质。'},
    {blueprint_section:'2.3',subtype:'error_discrimination',stem:'某离散LTI系统 \\(h[n]=(2)^nu[n]\\)。学生因其因果而判定稳定。正确结论是什么？',correct:'因果但不稳定，因为 \\(\\sum_n|h[n]|\\) 发散',wrong:[wrong('因果且稳定，因为 \\(h[n]\\) 有单位阶跃','CAUSALITY_ERROR'),wrong('非因果但稳定','CAUSALITY_ERROR'),wrong('是否稳定只看 \\(h[0]\\)','CONFUSE_ENERGY_POWER')],explanation:'正确：支撑在 \\(n\\ge0\\) 保证因果，但绝对和发散所以不稳定。错项把因果当稳定或只看单点。易错点：因果性与稳定性是独立条件。'},
    {blueprint_section:'2.3',subtype:'error_discrimination',stem:'已知 \\(x(t)\\to y(t)\\) 通过LTI系统。对输入 \\(x^{\\prime}(t)\\)，学生仍写输出 \\(y(t)\\)。正确改正是什么？',correct:'输出应为 \\(y^{\\prime}(t)\\)',wrong:[wrong('输出应为 \\(x^{\\prime}(t)y(t)\\)','CONFUSE_CONVOLUTION_MULTIPLICATION'),wrong('输出应为 \\(\\int y(t)dt\\)','FORGOT_INTEGRATION'),wrong('输出不变，因为系统时不变','OUTPUT_NOT_DIFFERENTIATED')],explanation:'正确：输入微分可与LTI卷积交换，输出也需同阶微分。错项混淆乘积、积分或把时不变误解为输出不变。易错点：时不变指移位响应，不是对所有变换都不变。'},
    {blueprint_section:'2.3',subtype:'error_discrimination',stem:'系统冲激响应 \\(h(t)=e^{-t}u(-t)\\) 的因果性与稳定性是什么？',correct:'非因果且不稳定',wrong:[wrong('因果且稳定','CAUSALITY_ERROR'),wrong('非因果但稳定','CONFUSE_ENERGY_POWER'),wrong('因果但不稳定','CAUSALITY_ERROR')],explanation:'正确：支撑在负时间所以非因果；当 \\(t\\to-\\infty\\) 时 \\(e^{-t}\\) 增长，绝对积分发散。错项只看指数符号或阶跃形式。易错点：判断衰减方向必须结合支撑区间。'}
  ],
  '2.4|concept':[
    {blueprint_section:'2.4',subtype:'concept',stem:'用常系数差分方程描述的系统，要直接视为LTI系统通常还需采用什么条件？',correct:'初始松弛（零初始条件）',wrong:[wrong('输入必须周期','WRONG_PERIOD'),wrong('输出必须为偶序列','IGNORED_CONJUGATE_SYMMETRY'),wrong('所有系数必须相等','LINEARITY_ERROR')],explanation:'正确：非零初始状态会引入与输入无关的响应，破坏零状态LTI映射的直接表述。错项加入无关限制。易错点：频率响应通常针对零状态响应。'},
    {blueprint_section:'2.4',subtype:'concept',stem:'差分方程中的项 \\(y[n-2]\\) 在频域对应什么因子乘以 \\(Y(e^{j\\omega})\\)？',correct:'\\(e^{-j2\\omega}\\)',wrong:[wrong('\\(e^{j2\\omega}\\)','SIGN_ERROR'),wrong('\\(j2\\omega\\)','CONFUSE_CT_DT'),wrong('\\(2e^{-j\\omega}\\)','WRONG_DELAY_FACTOR')],explanation:'正确：延迟2点对应乘 \\(e^{-j2\\omega}\\)。错项写反符号、混用微分性质或把延迟当幅度。易错点：延迟次数进入指数。'}
  ],
  '2.4|formula':[
    {blueprint_section:'2.4',subtype:'formula',stem:'零初始条件下，\\(y[n]-ay[n-1]=x[n]\\) 的频率响应是什么？',correct:'\\(H(e^{j\\omega})=\\frac1{1-ae^{-j\\omega}}\\)',wrong:[wrong('\\(\\frac1{1+ae^{-j\\omega}}\\)','SIGN_ERROR'),wrong('\\(1-ae^{-j\\omega}\\)','WRONG_DELAY_FACTOR'),wrong('\\(\\frac1{j\\omega-a}\\)','CONFUSE_CT_DT')],explanation:'正确：DTFT后 \\(Y(1-ae^{-j\\omega})=X\\)，再取 \\(Y/X\\)。错项改错符号、漏取倒数或混用连续时间形式。易错点：先把所有输出项因子提到一起。'},
    {blueprint_section:'2.4',subtype:'formula',stem:'连续系统满足 \\(y^{\\prime}(t)+3y(t)=2x(t)\\)，零初始时频率响应是哪一个？',correct:'\\(H(j\\omega)=\\frac{2}{j\\omega+3}\\)',wrong:[wrong('\\(\\frac{j\\omega+3}{2}\\)','WRONG_DIFFERENTIATION_FACTOR'),wrong('\\(\\frac{2}{j\\omega-3}\\)','SIGN_ERROR'),wrong('\\(\\frac{2}{e^{-j\\omega}+3}\\)','CONFUSE_CT_DT')],explanation:'正确：微分对应乘 \\(j\\omega\\)，所以 \\((j\\omega+3)Y=2X\\)。错项取倒数错误、符号错或混入离散延迟。易错点：频率响应是输出与输入之比。'}
  ],
  '2.4|error_discrimination':[
    {blueprint_section:'2.4',subtype:'error_discrimination',stem:'对 \\(y[n]+\\frac12y[n-1]=x[n-1]\\)，学生把右侧变换写成 \\(X(e^{j\\omega})\\)。漏掉了什么？',correct:'输入延迟因子 \\(e^{-j\\omega}\\)',wrong:[wrong('输出延迟因子 \\(e^{j\\omega}\\)','SIGN_ERROR'),wrong('幅度因子 \\(1/2\\)','MISS_SCALE_FACTOR'),wrong('连续时间因子 \\(j\\omega\\)','CONFUSE_CT_DT')],explanation:'正确：\\(x[n-1]\\) 的DTFT是 \\(e^{-j\\omega}X\\)。错项写反符号、混淆系数或时间类型。易错点：方程两侧每一个延迟都要单独变换。'},
    {blueprint_section:'2.4',subtype:'error_discrimination',stem:'学生由 \\(y^{\\prime}(t)+y(t)=x(t)\\) 写出 \\(H(j\\omega)=j\\omega+1\\)。核心错误是什么？',correct:'把分母多项式当成频率响应，正确应取倒数',wrong:[wrong('微分应对应 \\(e^{-j\\omega}\\)','CONFUSE_CT_DT'),wrong('常数1应写成 \\(2\\pi\\)','MISSING_2PI'),wrong('方程无法描述LTI系统','LINEARITY_ERROR')],explanation:'正确：变换后 \\((j\\omega+1)Y=X\\)，故 \\(H=Y/X=1/(j\\omega+1)\\)。错项混用离散性质或无关常数。易错点：先明确频率响应定义是 \\(Y/X\\)。'},
    {blueprint_section:'2.4',subtype:'error_discrimination',stem:'若差分方程含 \\(y[n+1]\\)，学生直接判定系统必非因果。这个判断为何不充分？',correct:'可重新移位方程；因果性要看能否由当前/过去输入和过去输出递推',wrong:[wrong('只要有输出项系统就因果','CAUSALITY_ERROR'),wrong('差分方程系统都非因果','CAUSALITY_ERROR'),wrong('因果性只由稳定性决定','CAUSALITY_ERROR')],explanation:'正确：索引整体平移可能把超前输出改写为当前输出，不能只看单个符号。错项使用过度概括。易错点：先整理成可实现递推式再判断因果。'},
    {blueprint_section:'2.4',subtype:'error_discrimination',stem:'在非零初始状态下直接用 \\(H=Y/X\\) 求系统全部输出，遗漏了什么？',correct:'零输入响应或初始条件贡献',wrong:[wrong('傅里叶变换的 \\(2\\pi\\) 因子','MISSING_2PI'),wrong('输入必须先时间反转','MISSING_TIME_REVERSAL'),wrong('输出必须取模平方','FORGOT_MAGNITUDE_SQUARED')],explanation:'正确：频率响应描述零状态输入输出关系，非零初始状态还会产生零输入响应。错项引入无关变换细节。易错点：先区分零状态响应与零输入响应。'}
  ],
  '2.5|concept':[
    {blueprint_section:'2.5',subtype:'concept',stem:'单位斜坡 \\(r(t)=tu(t)\\) 的一阶导数是什么？',correct:'\\(u(t)\\)',wrong:[wrong('\\(\\delta(t)\\)','CONFUSE_IMPULSE_STEP'),wrong('\\(t\\delta(t)\\)','CONFUSE_IMPULSE_STEP'),wrong('\\(1\\)','WRONG_SUPPORT_INTERVAL')],explanation:'正确：分布意义下 \\(d[tu(t)]/dt=u(t)+t\\delta(t)=u(t)\\)。错项把阶跃再微分、保留为普通常数或误解冲激乘积。易错点：\\(t\\delta(t)=0\\)。'}
  ],
  '2.5|error_discrimination':[
    {blueprint_section:'2.5',subtype:'error_discrimination',stem:'对 \\(a\\ne0\\)，\\(\\delta(at)\\) 的正确化简是什么？',correct:'\\(\\delta(at)=\\frac1{|a|}\\delta(t)\\)',wrong:[wrong('\\(\\delta(at)=\\frac1a\\delta(t)\\)','MISSING_ABSOLUTE_VALUE'),wrong('\\(\\delta(at)=|a|\\delta(t)\\)','MISS_SCALE_FACTOR'),wrong('\\(\\delta(at)=\\delta(t-a)\\)','WRONG_SHIFT_DIRECTION')],explanation:'正确：冲激尺度变化带来雅可比 \\(1/|a|\\)。错项漏绝对值、把因子倒置或误作平移。易错点：冲激尺度性质与普通函数不同。'},
    {blueprint_section:'2.5',subtype:'error_discrimination',stem:'表达式 \\(t\\delta(t)\\) 等于什么？',correct:'\\(0\\)',wrong:[wrong('\\(\\delta(t)\\)','CONFUSE_IMPULSE_STEP'),wrong('\\(t\\)','FORGOT_INTEGRATION'),wrong('\\(u(t)\\)','CONFUSE_IMPULSE_STEP')],explanation:'正确：冲激只在 \\(t=0\\) 取样，乘上的 \\(t\\) 在该点为0。错项忽略抽样性质或混淆阶跃。易错点：一般有 \\(f(t)\\delta(t)=f(0)\\delta(t)\\)。'},
    {blueprint_section:'2.5',subtype:'error_discrimination',stem:'信号 \\(u(t+1)-u(t-2)\\) 的导数是哪一个？',correct:'\\(\\delta(t+1)-\\delta(t-2)\\)',wrong:[wrong('\\(\\delta(t-1)-\\delta(t+2)\\)','WRONG_SHIFT_DIRECTION'),wrong('\\(u(t+1)-u(t-2)\\)','OUTPUT_NOT_DIFFERENTIATED'),wrong('\\(\\delta(t+1)+\\delta(t-2)\\)','SIGN_ERROR')],explanation:'正确：每个阶跃在原跳变位置产生同系数冲激。错项写反平移、漏微分或丢失负号。易错点：下降沿对应负冲激。'},
    {blueprint_section:'2.5',subtype:'error_discrimination',stem:'积分 \\(\\int_{-\\infty}^{\\infty}\\delta^{\\prime}(t)f(t)dt\\) 的正确结果是什么？',correct:'\\(-f^{\\prime}(0)\\)',wrong:[wrong('\\(f^{\\prime}(0)\\)','SIGN_ERROR'),wrong('\\(f(0)\\)','FORGOT_INTEGRATION'),wrong('\\(0\\)','CONFUSE_IMPULSE_STEP')],explanation:'正确：分部积分给出冲激导数作用于测试函数时带负号。错项漏负号、降错阶数或误判为0。易错点：\\(\\delta^{\\prime}\\) 的抽样结果是导数并带负号。'}
  ]
};

export const chapter2Catalog:ChapterCatalog=(section,subtype,index)=>
  choose(catalog[`${section}|${subtype}`]??[],index,`chapter2 ${section}|${subtype}`);
